server:
  port: 5388

spring:
  main:
    lazy-initialization: true

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/oxigenobd
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    cache: false
    suffix: .html

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  file:
    name: /var/lib/tomcat9/logs/oxigenowebservice.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: INFO
    org.springframework.web.client.RestTemplate: INFO
    org.apache.http: INFO
    httpclient.wire: INFO


jwt:
  secret: ubidata_2026_super_secret_key_1234567890
  expiration-ms: 86400000